//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICC.DataAccess.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICCEntities : DbContext
    {
        public ICCEntities()
            : base("name=ICCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookMachine> BookMachines { get; set; }
        public virtual DbSet<BuyFacility> BuyFacilities { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserAcount> UserAcounts { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
